# Note: ccx is a cc frontend that knows about the preprocessor.

CC =		cc/ccx
CFLAGS =	-DHOST=SYS_AMIGADOS -DOLD_PREPROCESSOR=1
OBJS =		cpp1.o cpp2.o cpp3.o cpp4.o cpp5.o cpp6.o

ncpp :		$(OBJS)
		$(CC) -o ncpp $(OBJS)

cpp1.o	:	cpp1.c cpp.h cppdef.h
		$(CC) $(CFLAGS) -c cpp1.c

cpp2.o	:	cpp2.c cpp.h cppdef.h
		$(CC) $(CFLAGS) -c cpp2.c

cpp3.o	:	cpp3.c cpp.h cppdef.h
		$(CC) $(CFLAGS) -c cpp3.c

cpp4.o	:	cpp4.c cpp.h cppdef.h
		$(CC) $(CFLAGS) -c cpp4.c

cpp5.o	:	cpp5.c cpp.h cppdef.h
		$(CC) $(CFLAGS) -c cpp5.c

cpp6.o	:	cpp6.c cpp.h cppdef.h
		$(CC) $(CFLAGS) -c cpp6.c
