#define YY_DEFAULT_ACTION ECHO;
#define FLEX_USE_ECS
#define FLEX_USE_MECS
/* A lexical scanner generated by flex */

#include "flexskeldef.h"

# line 1 "scan.l"
#define INITIAL 0
# line 2 "scan.l"
/*    SCAN.L   Lexical definition for ANSI "C", April 30, 1985 draf  */

/*****************************************************************
 *   This scanner was originally from Fred Fish disk #157 as a
 *   "C" grammar by William Loftus.  Both a scanner and a grammar
 *   were contributed; I use only the scanner.
 *  
 *  From the FF disk:

[FF157:grammars/readme.fnf]
This material was submitted to me on disk directly by William Loftus,
for inclusion in the library.

-Fred  ><>
22-Sep-88
--------
[FF157:grammars/C/README]
The files in this directory contain the ANSI C grammar from the April 30, 1985
draft of the proposed standard. This copy also incorporates all bug fixes I
have seen since the last two postings. With a little work this grammar can
be made to parse the C that most of us know and love (sort of).

There is one bug fix to the grammar that is in this posting. On line 295
of gram.y it previously read declaration_specifiers instead of
type_specifier_list as it does now. I believe the folks at the ANSI committee
made a mistake since if you replace the line with what the original read
you will end up with 16 shift/reduce errors and 2 reduce/reduce errors
(the good ones). As it is, it only has 1 shift/reduce error that occurs
on the if/else construct. YACC creates the correct parser and I don't want
to ugly my grammar up.

Anyway, all cumquats unite and generate this sucker. Then just sit and play
with it. Remember, the grammar accepts things like

    "Hello, world"++;
    --1.23456;
    *'a'

but this is not a bug, but simply a shuffling of the checking into the
semantic analysis. If you want to hack it up to do lvalue and rvalue
checking, I'm sure the ANSI committee would be glad to have your changes.
Don't send'em to me though. I don't want'em. Wear this in good health.

Jeff Lee
gatech!jeff	jeff@gatech	jeff%gatech.CSNet@CSNet-Relay.ARPA

 *
 ******************************************************************/


/*
 *    Successfull translated with Xenix 3.3 lex and FSF FLEX 1 "13 May 1987".
 *
 *    Mods:
 *        * Changed "CONST" into "CONST_T" to avoid symbol clashes with prog.
 *        * Hands off #-line processing.
 *
 *        'td_nest' goes to -1 upon EOF.  Done in get_tok().
 *
 *        input()  --  extents yytext string.
 *        unput()  --  prepares text for *next* token.
 *
 *        The following OCT pre-processor functions are defined:
 *        @selector( <selector> )     " @selector( at:putChar: ) "
 *                                    " MS_AT_PUTCHAR_ "
 *            converts selector into internal code.[25-july-89]
 *        @defs( <class_name> )       " @defs( Sequence ) "
 *                                    " Class isa; id contents; int capacity; "
 *            replaces with instance variable definition for class.[25-july-89]
 *        @includes
 *            inserts any includes the translator inserts.[10-aug-89]
 *      @protocol ClassName
 *          Creates template of methods for abstract classes.[29-oct-89]
 *        Allow "^+" and "^-" as token within expressions.[01-nov-89]
 *      @public
 *          Denotes following instance variables are public accessable
 *          [14-dec-90].
 *
 *        ******** Update to Version 4 of Objective-C ********
 *        These are defined:
 *            @interface
 *            @implementation
 *            @end
 *
 *        This file can be translated using lex from AT&T UNIX(tm). 
 *      Change the define 'IAM_FLEX', remove the #define'd for 'output',
 *      and expose the %p directive below.
 *        This was tested under Xenix.                [29-aug-89].
 *
 *        The Elipsis has been added.                 [03-mar-90].
 *        changed /strdup/ --> /newstring/            [12-apr-91].
 *
 *     28-May-91    bjw     <ctype.h> included from "oct.h"
 *    20-april-92  bjw    @abstract --> @protocol (for NeXT v2).
 */


/* vvvvvvvvvvvvvvvvvvv  User Servicable Parts Follow  vvvvvvvvvvvvvvvvvv */

#define  SW_WATCH_LINE	0

#define  IAM_FLEX	1
/*  %p size used only by UNIX lex: */
#if IAM_FLEX
#else
#endif
# line 121 "scan.l"

#define  SW_WATCH  0

#define  GRAMMAR  1


#include "oct.h"
#include "gram.h"


/*  Flex doesn't define this macro (remove if using UNIX lex): */
#if IAM_FLEX
# define  output(c)  fputc(c,yyout)
#endif

#ifndef TRUE
# define  TRUE   1
# define  FALSE  0
#endif


/* ^^^^^^^^^^^^^^^^  No User Servicable Parts Beyound  ^^^^^^^^^^^^^^^^^ */


void 	count();
void 	ne_count();
void	hash_line();
void 	hash_directive();
void 	comment();
void 	comment2();
int     check_type();
void	inc_td_cnt();
void	dec_td_cnt();

void	unput_last();
int     msg_parm();
int 	open_method();
void	ooc_selector( );
void	ooc_defs( );
void	ooc_includes( );
void	ooc_encode( );
void    ooc_public( );

# line 167 "scan.l"
#define YY_JAM 312
#define YY_JAM_BASE 600
#define YY_TEMPLATE 313
static char l[313] =
    {   0,
       -2,   -2,  106,  105,  105,   93,  106,   99,   92,  106,
       87,   88,   97,   96,   84,   95,   91,   98,   54,   54,
       85,   81,  100,   86,  101,  104,  106,   51,   89,   90,
      102,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   82,  103,   83,   94,
        5,   43,   44,  106,   80,    0,   59,    0,   66,   75,
       67,    0,    0,   64,   72,   62,   73,   63,   74,    0,
       57,    1,    2,   65,   58,   53,    0,   54,    0,   54,
       71,   77,   79,   78,   70,    0,    0,    0,    0,    0,
       51,   50,   68,   51,   51,   51,   51,   51,   51,   13,

       51,   51,   51,   51,   51,   51,   21,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   69,   76,
        0,    4,    0,    0,    0,    0,   55,   38,    0,   57,
       57,    0,   58,   53,    0,   56,   52,   61,   60,    0,
        0,    0,    0,    0,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   19,   51,   22,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,    0,    0,    0,    0,    0,    0,   57,
        0,   57,    0,   58,   56,   52,    0,    0,    0,    0,
        0,    6,   51,    8,    9,   51,   51,   51,   51,   15,

       16,   51,   51,   20,   23,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   35,   51,   51,    0,
       42,    0,    0,    0,    0,   57,   46,    0,    0,    0,
        0,    7,   10,   51,   51,   51,   51,   18,   51,   51,
       26,   51,   51,   51,   51,   51,   51,   33,   51,   51,
       37,    0,    0,    0,    0,    0,    0,    0,    0,   51,
       51,   14,   17,   51,   25,   27,   28,   29,   30,   31,
       51,   51,   51,    3,    0,    0,    0,   49,    0,   48,
        0,   51,   12,   51,   32,   51,   51,    0,    0,    0,
        0,    0,   11,   24,   34,   36,    0,    0,    0,   47,

       45,    0,    0,   41,    0,   39,    0,    0,    0,    0,
       40,    0
    } ;

static char e[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   31,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1
    } ;

static char m[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        4,    4,    4,    4,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1
    } ;

static short int b[317] =
    {   0,
        0,   60,  600,  600,  600,  576,   62,  575,   60,  562,
      600,  600,  573,   56,  600,   57,   58,   70,   82,   89,
      600,  600,   48,  572,   61,  600,   50,  574,  600,  600,
      570,   69,   58,   89,  102,   98,   68,   75,   86,   92,
      108,  113,   79,  112,  103,  115,  600,  119,  600,  600,
      146,  138,  151,  131,  600,  144,  600,  590,  600,  600,
      600,  143,  154,  600,  600,  600,  600,  600,  600,  575,
      162,  600,  600,  600,  169,  190,  201,  192,    0,  211,
      567,  600,  600,  600,  566,  546,  537,  536,  529,  542,
      563,  600,  600,  147,  150,  135,  175,  149,  164,  181,

      195,  205,  176,  183,  213,  208,  562,  215,  206,  216,
      221,  224,  227,  230,  225,  232,  235,  238,  600,  600,
      256,  600,  535,  530,  238,  198,  600,  600,  276,  600,
      274,  293,  600,  265,  280,  296,  278,  600,  600,  536,
      538,  537,  537,  527,  249,  244,  259,  270,  287,  298,
      299,  304,  300,  308,  309,  554,  310,  553,  311,  312,
      313,  315,  317,  320,  323,  325,  328,  331,  333,  334,
      336,  332,  337,  522,  319,  519,  324,  519,  347,  357,
      374,  600,  353,  372,  600,  363,  515,  517,  519,  518,
      523,  544,  362,  543,  542,  343,  376,  354,  377,  541,

      540,  379,  382,  539,  538,  384,  386,  387,  388,  392,
      394,  393,  396,  403,  397,  401,  537,  398,  404,  514,
      600,  507,  512,  498,  408,  430,  600,  511,  495,  504,
      509,  528,  527,  408,  409,  414,  415,  526,  411,  421,
      525,  431,  432,  430,  434,  435,  440,  524,  442,  444,
      523,  541,  499,  487,  488,  496,  496,  496,  480,  443,
      447,  514,  513,  449,  512,  511,  510,  509,  508,  507,
      454,  456,  448,  525,  476,  481,  483,  600,  480,  600,
      470,  459,  496,  457,  489,  463,  461,  466,  469,  455,
      451,  447,  475,  474,  473,  468,  437,  446,  437,  600,

      600,  429,  231,  600,  224,  600,  131,  130,   52,   44,
      600,  600,  511,  515,  517,   88
    } ;

static short int d[317] =
    {   0,
      312,    1,  312,  312,  312,  312,  313,  312,  312,  314,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  315,  312,  312,
      312,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  313,  312,  313,  312,  312,
      312,  314,  314,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  316,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      315,  312,  312,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  316,  312,  312,  312,
      312,  312,  312,  312,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  312,  312,  312,  312,  312,  312,  312,  312,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  312,  312,  312,  312,  312,  312,  312,
      312,  315,  315,  315,  315,  315,  315,  312,  312,  312,
      312,  312,  315,  315,  315,  315,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,-32767,  312,  312,  312,  312
    } ;

static short int n[667] =
    {   0,
        3,    4,    5,    4,    6,    7,    3,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   28,   29,    3,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   28,   39,   28,   40,   28,
       28,   28,   28,   41,   42,   43,   44,   45,   46,   28,
       28,   28,   47,   48,   49,   50,   51,   57,   60,   65,
       81,   82,   67,   52,   70,   53,   71,   71,   92,   66,
       68,   69,   72,   61,   84,   85,   54,   73,   92,   92,
      137,   86,   87,   74,  311,   92,   88,   58,   75,   92,

       76,   76,   89,  310,   90,   75,   92,   80,   80,   92,
       77,   95,   92,   78,   78,   79,  104,   77,   92,  105,
       78,   78,   92,   92,   77,   94,  106,   96,   92,  107,
       78,   77,   92,   92,   97,   92,  108,   78,   78,  115,
       98,   79,  119,  109,   99,   78,  101,  121,  102,   57,
      110,   65,  127,  100,  117,   92,  312,  103,  111,  112,
      118,   66,  116,   62,  122,  122,   67,   92,  113,   92,
       92,  114,   86,  124,   68,   69,  309,  125,   63,   58,
       71,   71,  120,  126,   92,   90,  308,  131,  131,  147,
      129,  130,  146,  130,  123,   92,   92,  132,  133,  149,

      133,   92,  145,   92,  129,  130,   75,  150,   76,   76,
      130,  132,  133,  148,  135,   92,  135,  133,   77,  136,
      136,  134,  134,   78,   78,   92,   92,   75,   92,   80,
       80,  154,   77,   92,  155,   92,   92,  151,  134,   77,
       78,   92,   78,   78,   92,   92,  134,   92,   78,  152,
       92,  178,   92,   77,  143,   92,  159,  121,   92,   78,
      160,  153,  307,  157,   92,  165,  156,   78,  163,   92,
      158,  161,  162,  306,  122,  122,  167,  168,  169,   92,
      166,  171,  193,  172,  173,  164,  170,  176,  177,  179,
       92,  179,  131,  131,  180,  180,  134,  134,  136,  136,

      192,  194,  181,  182,  123,  182,  183,   92,  183,  186,
      186,  184,  184,  134,  136,  136,  181,  182,   92,   92,
       92,  134,  182,  195,   92,  185,  186,  185,   92,   92,
       92,   92,   92,   92,  186,   92,  198,   92,  199,  185,
       92,  196,  197,   92,  185,   92,  200,  203,   92,  201,
      202,   92,   92,   92,   92,  205,   92,   92,  206,  188,
      221,  204,  210,   92,  189,  180,  180,  209,  208,  207,
      218,  184,  184,  214,   92,  180,  180,  217,  211,  223,
      216,  212,   92,  213,  215,  219,  130,  225,  130,  225,
      184,  184,  226,  226,  186,  186,   92,   92,  233,   92,

      130,  133,   92,  133,   92,  130,   92,   92,   92,  232,
      235,  186,   92,   92,   92,  133,   92,   92,   92,  186,
      133,   92,  234,   92,   92,  236,  226,  226,   92,   92,
      242,   92,  237,  245,   92,   92,  246,  238,  239,  240,
      244,   92,  241,  243,  247,  249,  251,  248,  226,  226,
       92,   92,   92,  250,   92,   92,  262,  261,  260,  182,
       92,  182,   92,   92,   92,  263,  264,   92,   92,   92,
      268,  265,  266,  182,   92,  267,   92,   92,  182,   92,
      270,   92,  271,   92,  305,  304,  303,  302,   92,  269,
      273,  284,  272,   92,   92,   92,  287,  285,  286,  282,

      301,  293,  283,  296,  295,  300,  299,  298,  297,   92,
      294,   56,   56,   56,   56,   62,   92,   62,   62,   91,
       91,  292,  291,  290,  289,  288,  274,   92,   92,   92,
       92,   92,   92,   92,   92,  281,  280,  279,  278,  277,
      276,  275,  274,   92,   92,   92,   92,   92,   92,  259,
      258,  257,  256,  255,  254,  253,  252,   92,   92,   92,
       92,   92,   92,   92,   92,  231,  230,  229,  228,  227,
      224,  222,  220,   92,   92,  191,  190,  189,  188,  187,
      175,  174,   92,   92,  144,  143,  142,  141,  140,  139,
      138,  128,  312,   93,   92,   83,   64,   63,   59,   55,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312
    } ;

static short int c[667] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    7,    9,   14,
       23,   23,   16,    2,   17,    2,   17,   17,   33,   14,
       16,   16,   18,    9,   25,   25,    2,   18,   37,   32,
      316,   27,   27,   18,  310,   38,   27,    7,   19,   43,

       19,   19,   27,  309,   27,   20,   39,   20,   20,   34,
       19,   33,   40,   19,   19,   19,   37,   20,   36,   37,
       20,   20,   35,   45,   19,   32,   38,   34,   41,   39,
       19,   20,   44,   42,   34,   46,   39,   20,   19,   43,
       34,   19,   48,   40,   35,   20,   36,   51,   36,   56,
       41,   52,   62,   35,   45,   96,   63,   36,   42,   42,
       46,   52,   44,   63,   51,   51,   53,   94,   42,   98,
       95,   42,   54,   54,   53,   53,  308,   54,   62,   56,
       71,   71,   48,   54,   99,   54,  307,   75,   75,   96,
       71,   71,   95,   71,   51,   97,  103,   75,   75,   98,

       75,  100,   94,  104,   71,   71,   76,   99,   76,   76,
       71,   75,   75,   97,   77,  101,   77,   75,   76,   77,
       77,   76,   76,   78,   78,  102,  109,   80,  106,   80,
       80,  103,   76,  105,  104,  108,  110,  100,   76,   80,
       78,  111,   80,   80,  112,  115,   76,  113,   78,  101,
      114,  126,  116,   80,  126,  117,  109,  121,  118,   80,
      110,  102,  305,  106,  146,  113,  105,   80,  112,  145,
      108,  110,  111,  303,  121,  121,  114,  115,  116,  147,
      113,  117,  146,  117,  118,  112,  116,  125,  125,  129,
      148,  129,  131,  131,  129,  129,  134,  134,  135,  135,

      145,  147,  131,  131,  121,  131,  132,  149,  132,  137,
      137,  132,  132,  134,  136,  136,  131,  131,  150,  151,
      153,  134,  131,  148,  152,  136,  137,  136,  154,  155,
      157,  159,  160,  161,  137,  162,  150,  163,  151,  136,
      164,  149,  149,  165,  136,  166,  152,  155,  167,  153,
      154,  168,  172,  169,  170,  159,  171,  173,  160,  175,
      175,  157,  164,  196,  177,  179,  179,  163,  162,  161,
      172,  183,  183,  168,  198,  180,  180,  171,  165,  177,
      170,  166,  193,  167,  169,  173,  180,  181,  180,  181,
      184,  184,  181,  181,  186,  186,  197,  199,  196,  202,

      180,  184,  203,  184,  206,  180,  207,  208,  209,  193,
      198,  186,  210,  212,  211,  184,  213,  215,  218,  186,
      184,  216,  197,  214,  219,  199,  225,  225,  234,  235,
      209,  239,  202,  212,  236,  237,  213,  203,  206,  207,
      211,  240,  208,  210,  214,  216,  219,  215,  226,  226,
      244,  242,  243,  218,  245,  246,  236,  235,  234,  226,
      247,  226,  249,  260,  250,  237,  239,  261,  273,  264,
      244,  240,  242,  226,  271,  243,  272,  284,  226,  282,
      246,  287,  247,  286,  302,  299,  298,  297,  296,  245,
      250,  264,  249,  295,  294,  293,  273,  271,  272,  260,

      292,  282,  261,  287,  286,  291,  290,  289,  288,  285,
      284,  313,  313,  313,  313,  314,  283,  314,  314,  315,
      315,  281,  279,  277,  276,  275,  274,  270,  269,  268,
      267,  266,  265,  263,  262,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  248,  241,  238,  233,  232,  231,
      230,  229,  228,  224,  223,  222,  220,  217,  205,  204,
      201,  200,  195,  194,  192,  191,  190,  189,  188,  187,
      178,  176,  174,  158,  156,  144,  143,  142,  141,  140,
      124,  123,  107,   91,   90,   89,   88,   87,   86,   85,
       81,   70,   58,   31,   28,   24,   13,   10,    8,    6,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312
    } ;


/* these declarations have to come after the section 1 code or lint gets
 * confused about whether the variables are used
 */
FILE *yyin = stdin, *yyout = stdout;

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
static int yy_start, yy_b_buf_p, yy_c_buf_p, yy_e_buf_p;
static int yy_saw_eof, yy_init = 1;

/* yy_ch_buf has to be 1 character longer than YY_BUF_SIZE, since when
 * setting up yytext we can try to put a '\0' just past the end of the
 * matched text
 */
static char yy_ch_buf[YY_BUF_SIZE + 1];
static int yy_st_buf[YY_BUF_SIZE];
static char yy_hold_char;
char *yytext;
static int yyleng;

YY_DECL
    {
    int yy_n_chars, yy_lp, yy_iii, yy_buf_pos, yy_act;



    if ( yy_init )
        {
        YY_INIT;
        yy_start = 1;
        yy_init = 0;
        }

    goto get_next_token;

do_action:
    for ( ; ; )
        {
        YY_DO_BEFORE_ACTION

#ifdef FLEX_DEBUG
        fprintf( stderr, "--accepting rule #%d\n", yy_act );
#endif
        switch ( yy_act )
            {
case 1:
# line 168 "scan.l"
{ comment(); }
	YY_BREAK
case 2:
# line 169 "scan.l"
{ comment2(); }
	YY_BREAK
case 3:
# line 170 "scan.l"
{ hash_line(1); }
	YY_BREAK
case 4:
# line 171 "scan.l"
{ unput_last(); hash_line(1); }
	YY_BREAK
case 5:
# line 172 "scan.l"
{ hash_directive(); }   /* Catch-all */
	YY_BREAK
case 6:
# line 174 "scan.l"
{ count(); return(T_AUTO); }
	YY_BREAK
case 7:
# line 175 "scan.l"
{ count(); return(BREAK); }
	YY_BREAK
case 8:
# line 176 "scan.l"
{ count(); return(CASE); }
	YY_BREAK
case 9:
# line 177 "scan.l"
{ count(); return(T_CHAR); }
	YY_BREAK
case 10:
# line 178 "scan.l"
{ count(); return(T_CONST); }
	YY_BREAK
case 11:
# line 179 "scan.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 12:
# line 180 "scan.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 13:
# line 181 "scan.l"
{ count(); return(DO); }
	YY_BREAK
case 14:
# line 182 "scan.l"
{ count(); return(T_DOUBLE); }
	YY_BREAK
case 15:
# line 183 "scan.l"
{ count(); return(ELSE); }
	YY_BREAK
case 16:
# line 184 "scan.l"
{ count(); return(T_ENUM); }
	YY_BREAK
case 17:
# line 185 "scan.l"
{ count(); return(T_EXTERN); }
	YY_BREAK
case 18:
# line 186 "scan.l"
{ count(); return(T_FLOAT); }
	YY_BREAK
case 19:
# line 187 "scan.l"
{ count(); return(FOR); }
	YY_BREAK
case 20:
# line 188 "scan.l"
{ count(); return(GOTO); }
	YY_BREAK
case 21:
# line 189 "scan.l"
{ count(); return(IF); }
	YY_BREAK
case 22:
# line 190 "scan.l"
{ count(); return(T_INT); }
	YY_BREAK
case 23:
# line 191 "scan.l"
{ count(); return(T_LONG); }
	YY_BREAK
case 24:
# line 192 "scan.l"
{ count(); return(T_REGISTER); }
	YY_BREAK
case 25:
# line 193 "scan.l"
{ count(); return(RETURN); }
	YY_BREAK
case 26:
# line 194 "scan.l"
{ count(); return(T_SHORT); }
	YY_BREAK
case 27:
# line 195 "scan.l"
{ count(); return(T_SIGNED); }
	YY_BREAK
case 28:
# line 196 "scan.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 29:
# line 197 "scan.l"
{ count(); return(T_STATIC); }
	YY_BREAK
case 30:
# line 198 "scan.l"
{ count(); return(T_STRUCT); }
	YY_BREAK
case 31:
# line 199 "scan.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 32:
# line 200 "scan.l"
{ count(); return(T_TYPEDEF); }
	YY_BREAK
case 33:
# line 201 "scan.l"
{ count(); return(T_UNION); }
	YY_BREAK
case 34:
# line 202 "scan.l"
{ count(); return(T_UNSIGNED); }
	YY_BREAK
case 35:
# line 203 "scan.l"
{ count(); return(T_VOID); }
	YY_BREAK
case 36:
# line 204 "scan.l"
{ count(); return(T_VOLATILE); }
	YY_BREAK
case 37:
# line 205 "scan.l"
{ count(); return(WHILE); }
	YY_BREAK
case 38:
# line 206 "scan.l"
{ count(); return(ELIPSIS); }
	YY_BREAK
case 39:
# line 209 "scan.l"
{ ne_count(); return(OPEN_INTERFACE); }
	YY_BREAK
case 40:
# line 210 "scan.l"
{ ne_count(); return(OPEN_IMPLEMENTATION); }
	YY_BREAK
case 41:
# line 211 "scan.l"
{ ne_count(); return(OPEN_PROTOCOL); }
	YY_BREAK
case 42:
# line 212 "scan.l"
{ ne_count(); return(CLOSE_END); }
	YY_BREAK
case 43:
# line 213 "scan.l"
{ return open_method();  }
	YY_BREAK
case 44:
# line 214 "scan.l"
{ return open_method();  }
	YY_BREAK
case 45:
# line 216 "scan.l"
{  ooc_selector( ); }
	YY_BREAK
case 46:
# line 217 "scan.l"
{  ooc_defs( );     }
	YY_BREAK
case 47:
# line 218 "scan.l"
{  ooc_includes( );	}
	YY_BREAK
case 48:
# line 220 "scan.l"
{  ooc_public( );  }
	YY_BREAK
case 49:
# line 221 "scan.l"
{  ooc_encode( );	}
	YY_BREAK
case 50:
# line 224 "scan.l"
{          return(msg_parm()); }
	YY_BREAK
case 51:
# line 225 "scan.l"
{ count(); return(check_type()); }
	YY_BREAK
case 52:
# line 228 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 53:
# line 229 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 54:
# line 230 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 55:
# line 231 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 56:
# line 233 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 57:
# line 234 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 58:
# line 235 "scan.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 59:
# line 237 "scan.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 60:
# line 239 "scan.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 61:
# line 240 "scan.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 62:
# line 241 "scan.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 63:
# line 242 "scan.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 64:
# line 243 "scan.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 65:
# line 244 "scan.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 66:
# line 245 "scan.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 67:
# line 246 "scan.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 68:
# line 247 "scan.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 69:
# line 248 "scan.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 70:
# line 249 "scan.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 71:
# line 250 "scan.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 72:
# line 251 "scan.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 73:
# line 252 "scan.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 74:
# line 253 "scan.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 75:
# line 254 "scan.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 76:
# line 255 "scan.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 77:
# line 256 "scan.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 78:
# line 257 "scan.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 79:
# line 258 "scan.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 80:
# line 259 "scan.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 81:
# line 260 "scan.l"
{ count(); return(';'); }
	YY_BREAK
case 82:
# line 261 "scan.l"
{ count(); inc_td_cnt(); return(CH_LCURLY); }
	YY_BREAK
case 83:
# line 262 "scan.l"
{ count(); dec_td_cnt(); return(CH_RCURLY); }
	YY_BREAK
case 84:
# line 263 "scan.l"
{ count(); return(','); }
	YY_BREAK
case 85:
# line 264 "scan.l"
{ count(); return(':'); }
	YY_BREAK
case 86:
# line 265 "scan.l"
{ count(); return('='); }
	YY_BREAK
case 87:
# line 267 "scan.l"
{ count(); return('('); }
	YY_BREAK
case 88:
# line 268 "scan.l"
{ count(); return(')'); }
	YY_BREAK
case 89:
# line 269 "scan.l"
{ count(); inc_td_cnt(); return('['); }
	YY_BREAK
case 90:
# line 270 "scan.l"
{ count(); dec_td_cnt(); return(']'); }
	YY_BREAK
case 91:
# line 272 "scan.l"
{ count(); return('.'); }
	YY_BREAK
case 92:
# line 273 "scan.l"
{ count(); return('&'); }
	YY_BREAK
case 93:
# line 274 "scan.l"
{ count(); return('!'); }
	YY_BREAK
case 94:
# line 275 "scan.l"
{ count(); return('~'); }
	YY_BREAK
case 95:
# line 276 "scan.l"
{ count(); return('-'); }
	YY_BREAK
case 96:
# line 277 "scan.l"
{ count(); return('+'); }
	YY_BREAK
case 97:
# line 278 "scan.l"
{ count(); return('*'); }
	YY_BREAK
case 98:
# line 279 "scan.l"
{ count(); return('/'); }
	YY_BREAK
case 99:
# line 280 "scan.l"
{ count(); return('%'); }
	YY_BREAK
case 100:
# line 281 "scan.l"
{ count(); return('<'); }
	YY_BREAK
case 101:
# line 282 "scan.l"
{ count(); return('>'); }
	YY_BREAK
case 102:
# line 283 "scan.l"
{ count(); return('^'); }
	YY_BREAK
case 103:
# line 284 "scan.l"
{ count(); return('|'); }
	YY_BREAK
case 104:
# line 285 "scan.l"
{ count(); return('?'); }
	YY_BREAK
case 105:
# line 287 "scan.l"
{ count(); }
	YY_BREAK
case 106:
# line 288 "scan.l"
{ /* ignore bad characters */ }
	YY_BREAK

case YY_NEW_FILE:
break; /* begin reading from new file */

case YY_DO_DEFAULT:
YY_DEFAULT_ACTION;
break;

case YY_END_TOK:
return ( YY_END_TOK );

default:
YY_FATAL_ERROR( "fatal flex scanner internal error" );
            }

get_next_token:
        {
        register int yy_curst;
        register char yy_sym;

        YY_DO_BEFORE_SCAN

        /* set up to begin running DFA */

        yy_curst = yy_start;

        if ( yy_ch_buf[yy_c_buf_p] == '\n' )
            ++yy_curst;

        /* yy_b_buf_p points to the position in yy_ch_buf
         * of the start of the current run.
         */

        yy_b_buf_p = yy_c_buf_p + 1;

        do /* until the machine jams */
            {
            if ( yy_c_buf_p == yy_e_buf_p )
                { /* need more input */
                if ( yy_e_buf_p >= YY_BUF_LIM )
                    { /* not enough room to do another read */
                    /* see if we can make some room for more chars */

                    yy_n_chars = yy_e_buf_p - yy_b_buf_p;

                    if ( yy_n_chars >= 0 )
                        /* shift down buffer to make room */
                        for ( yy_iii = 0; yy_iii <= yy_n_chars; ++yy_iii )
                            {
                            yy_buf_pos = yy_b_buf_p + yy_iii;
                            yy_ch_buf[yy_iii] = yy_ch_buf[yy_buf_pos];
                            yy_st_buf[yy_iii] = yy_st_buf[yy_buf_pos];
                            }

                    yy_b_buf_p = 0;
                    yy_e_buf_p = yy_n_chars;

                    if ( yy_e_buf_p >= YY_BUF_LIM )
                        YY_FATAL_ERROR( "flex input buffer overflowed" );

                    yy_c_buf_p = yy_e_buf_p;
                    }

                else if ( yy_saw_eof )
                    {
saweof:             if ( yy_b_buf_p > yy_e_buf_p )
                        {
                        if ( yywrap() )
                            {
                            yy_act = YY_END_TOK;
                            goto do_action;
                            }

                        else
                            {
                            YY_INIT;
                            yy_act = YY_NEW_FILE;
                            goto do_action;
                            }
                        }

                    else /* do a jam to eat up more input */
                        {
#ifndef FLEX_INTERACTIVE_SCANNER
                        /* we're going to decrement yy_c_buf_p upon doing
                         * the jam.  In this case, that's wrong, since
                         * it points to the last non-jam character.  So
                         * we increment it now to counter the decrement.
                         */
                        ++yy_c_buf_p;
#endif
                        break;
                        }
                    }

                YY_INPUT( (yy_ch_buf + yy_c_buf_p + 1), yy_n_chars,
                          YY_MAX_LINE );

                if ( yy_n_chars == YY_NULL )
                    {
                    if ( yy_saw_eof )
        YY_FATAL_ERROR( "flex scanner saw EOF twice - shouldn't happen" );
                    yy_saw_eof = 1;
                    goto saweof;
                    }

                yy_e_buf_p += yy_n_chars;
                }

            ++yy_c_buf_p;

#ifdef FLEX_USE_ECS
            yy_sym = e[yy_ch_buf[yy_c_buf_p]];
#else
            yy_sym = yy_ch_buf[yy_c_buf_p];
#endif

#ifdef FLEX_FULL_TABLE
            yy_curst = n[yy_curst][yy_sym];

#else /* get next state from compressed table */

            while ( c[b[yy_curst] + yy_sym] != yy_curst )
                {
                yy_curst = d[yy_curst];

#ifdef FLEX_USE_MECS
                /* we've arrange it so that templates are never chained
                 * to one another.  This means we can afford make a
                 * very simple test to see if we need to convert to
                 * yy_sym's meta-equivalence class without worrying
                 * about erroneously looking up the meta-equivalence
                 * class twice
                 */

                if ( yy_curst >= YY_TEMPLATE )
                    yy_sym = m[yy_sym];
#endif
                }

            yy_curst = n[b[yy_curst] + yy_sym];

#endif

            yy_st_buf[yy_c_buf_p] = yy_curst;

            }
#ifdef FLEX_INTERACTIVE_SCANNER
        while ( b[yy_curst] != YY_JAM_BASE );
#else
        while ( yy_curst != YY_JAM );
        --yy_c_buf_p; /* put back character we jammed on */

#endif

        if ( yy_c_buf_p >= yy_b_buf_p )
            { /* we matched some text */
            yy_curst = yy_st_buf[yy_c_buf_p];
            yy_lp = l[yy_curst];

#ifdef FLEX_REJECT_ENABLED
find_rule: /* we branch to this label when doing a REJECT */
#endif

            for ( ; ; ) /* until we find what rule we matched */
                {
#ifdef FLEX_REJECT_ENABLED
                if ( yy_lp && yy_lp < l[yy_curst + 1] )
                    {
                    yy_act = a[yy_lp];
                    goto do_action; /* "continue 2" */
                    }
#else
                if ( yy_lp )
                    {
                    yy_act = yy_lp;
                    goto do_action; /* "continue 2" */
                    }
#endif

                if ( --yy_c_buf_p < yy_b_buf_p )
                    break;

                yy_curst = yy_st_buf[yy_c_buf_p];
                yy_lp = l[yy_curst];
                }
            }

        /* if we got this far, then we didn't find any accepting
         * states
         */

        /* so that the default applies to the first char read */
        ++yy_c_buf_p;

        yy_act = YY_DO_DEFAULT;
        }
        }

    /*NOTREACHED*/
    }


static int unput( c )
char c;

    {
    YY_DO_BEFORE_SCAN; /* undo effects of setting up yytext */

    if ( yy_c_buf_p == 0 )
        {
        register int i;
        register int yy_buf_pos = YY_BUF_MAX;

        for ( i = yy_e_buf_p; i >= yy_c_buf_p; --i )
            {
            yy_ch_buf[yy_buf_pos] = yy_ch_buf[i];
            yy_st_buf[yy_buf_pos] = yy_st_buf[i];
            --yy_buf_pos;
            }

        yy_c_buf_p = YY_BUF_MAX - yy_e_buf_p;
        yy_e_buf_p = YY_BUF_MAX;
        }

    if ( yy_c_buf_p <= 0 )
        YY_FATAL_ERROR( "flex scanner push-back overflow" );

    if ( yy_c_buf_p >= yy_b_buf_p && yy_ch_buf[yy_c_buf_p] == '\n' )
        yy_ch_buf[yy_c_buf_p - 1] = '\n';

    yy_ch_buf[yy_c_buf_p--] = c;

    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


static int input()

    {
    int c;

    YY_DO_BEFORE_SCAN

    if ( yy_c_buf_p == yy_e_buf_p )
        { /* need more input */
        int yy_n_chars;

        /* we can throw away the entire current buffer */
        if ( yy_saw_eof )
            {
            if ( yywrap() )
                return ( EOF );

            YY_INIT;
            }

        yy_b_buf_p = 0;
        YY_INPUT( yy_ch_buf, yy_n_chars, YY_MAX_LINE );

        if ( yy_n_chars == YY_NULL )
            {
            yy_saw_eof = 1;

            if ( yywrap() )
                return ( EOF );

            YY_INIT;

            return ( input() );
            }

        yy_c_buf_p = -1;
        yy_e_buf_p = yy_n_chars - 1;
        }

    c = yy_ch_buf[++yy_c_buf_p];

    YY_DO_BEFORE_ACTION;

    return ( c );
    }
# line 290 "scan.l"


/* ----------------------  Handling Code  ------------------------------- */


#define  SIZ_BUFFER   120

unsigned    lineat = 1, column = 0;
/* save_text and texts are defined in main.c (via oct.h when MAIN); do not redefine here */
int     	trip_hline;

/*  Result of scan_next_word() stored here:  */
static char  scan_keep[ SIZ_BUFFER+2 ];


/*   yywhitespace  --  Eat whitespace upto next token, but preserve
 *                     the next token.  Track our column/lineat counters.
 *    Outline:
 *         while( isspace(nextByte) )
 *             eat char,
 *             update lineat/column counters.
 */
    void
yywhitespace()
{
	int    c;
	char   newline = FALSE;

	while( (c=input()) != 0 && isspace(c) )
    {
	    /*  Calc position of this char: */
		switch( c )
		{
			case '\f' :
			case '\n' :
			        ++lineat ;
					column  = 0;
			        newline = TRUE;
					break ;

			case '\t' :
			        column += 8 - (column%8) ;
					break ;

			default :
			        ++column;
					break ;
		}
	}
	/*  Now restore and summarize: */
    unput(c);
	if( newline )
    {
		unput( '\n' );
		--lineat;
    }
}   /* yywhitespace */


/*   scan_next_word  --  Manually read ahead for next token.  Will not
 *                       move off current line.  Ie, EOLN terminates
 *                       search unsuccessfully.  Returns 0 if errors.
 *            Returns last char is scan_keep[] contains valid string.
 */
    static int
scan_next_word( )
{
    register char	*p;
    register int  	c;
    int        last = ' ';

    /*  Skip to next word (skip horizontal space):  */
    while( (c=input()) == ' ' || c == '\t' )
        ;;
    switch( c )
    {
	case 0 :
            return 0;

	case '"' :
            last = c;
            c = input();            /* Skip quotes */
            break ;

	case CH_OPEN_PAREN :
            last = CH_CLOSE_PAREN;
            c = input();             /* Find first close paren */
            break ;
    }

    for( p = (&scan_keep[0]) ;
         p < &scan_keep[SIZ_BUFFER] && c != last && c != '\n' && c != '\0' ;
         c = input() )
    {
        *p++ = c;
    }
    *p = '\0' ;

    if( c != last )
        unput( c );

    return( c );
}   /* scan_next_word */


/*   unput_last  --  Unput the last char of current token.
*/
    void
unput_last()
{
    yyless( yyleng-1 );
}


/*  comment  --  Do a slash-star comment.  Whole comment is eaten.
*/
    void
comment()
{
        char c, c1;

 loop:
        while ((c = input()) != '*' && c != 0)
            if( c == '\n' )
                ++lineat;

        if ((c1 = input()) != '/' && c != 0)
        {
                unput(c1);
                goto loop;
        }
}   /* comment */


/*   comment2  --  Do a slash-slash comment until end of line.  Eat me.
*/
    void
comment2( )
{
    int   c;

    while( (c=input()) != '\n' && c != 0 )
        ;
    unput( '\n' );
}   /* comment2 */


    void
hash_line( grabit_flag )
    int 	grabit_flag;
{
    extern int   atoi();
    extern char  *src_filename;

    char    *last;
    int 	c = 0, flag = 0;

    last = "\n" ;
    if( grabit_flag > 0 )
    {
        /* update name and position: */
        /*  #line  <line_number>  ["<filename>"]  */
        /*        ^-- inbuff ptr                  */

        flag = 1;
        last = "";
        if( (c=scan_next_word()) > 0 && strlen(scan_keep) > 0 )
        {
            lineat = atoi( scan_keep );
            if( lineat > 4 )      /* Prevent '#line 0' from appearing */
            {
                --lineat;
                last = "\n" ;
            }

            flag = 2;
            c = scan_next_word();
            if( strlen(scan_keep) > 0 )
            {
                MFREE( src_filename );
                src_filename = newstring( scan_keep );
            }
        }

#if SW_WATCH_LINE
        printf( "(hashline) flag=%d, lineat=%u.\n", flag, lineat );
#endif
        if( c != '\n' && c != 0 )
        {
     	    for ( ; c != '\n' && c != 0 ; c=input() )
                ;;
      	    unput( c );         /* Give back newline */
        }
    } 

    fprintf( yyout, "#line %u \"%s\"%s", lineat, src_filename, last );

}   /* hash_line */


/*   hash_directive  --  Catch hash-directives that aren't "#line" stuff.
 *                       These directives are copied verbatum (kinda).
 */
    void
hash_directive()
{
    register int   c;

 	output( '#' );              /* Scanner ate this, so output it again */

    c = input();
 LOOP:
    while( c != '\\' && c != '\n' && c != '\0' )
    {
        output(c);
        c = input();
    }

    /* If this line continues, advance to next line and continue copying! */
    if( c == '\\' )
    {
        output( c );
        if( (c=input()) == '\n' )
        {
            output('\n');
            ++lineat;
            c = input();
        }
        goto  LOOP;
    }

    /*  'c' is either end-of-file, or newline: */
    if( c == '\n' )
        unput( c );

}   /* hash_directive */


#if 0
/*   unget_newline  --  Hack to spit out another newline and back up the
 *                      line counter.  We hope that soon a #line directive
 *                      will be outputted to resynch the world.  KLUDGE!!
 */
    void
unget_newline()
{

    --lineat;
    unput( '\n' );
}   /* unget_newline */
#endif


/*   all_count  --  Maintain line and column counter for the token just
//                  accepted.  If we're in a collection mode for lex_text(),
//                  then append a parameter separator symbol.  Special
//                  care is taken to not add too many separators.  Also,
//           any byte sized value may be the separator, so lots of
//           conditionals exist to test against.  If you change anything
//           here, better run a complete test suite against the new code!
*/
    void
all_count( echoFlag )
    int   echoFlag;
{
    /* static char  sep[2] = { CH_PARM_SEP, '\0' } ; */
    register char	*t;
    register int  ch;

    if( trip_hline && !save_text && (yytext[0] == '\n') )
    {
        trip_hline = 0;
        {  fprintf( yyout, " /%c vvv trip_hline vvv %c/\n", '*', '*' );  }
        hash_line(-1);            /* Re-synch 'cc' with input file */
    }

    /* if( echoFlag && !in_class_def && !in_method_def ) */
    if( echoFlag && 
       ((in_state   & (IS_SEEN_IF|IS_CLASS_DEF|IS_METHOD_DEF)) == 0 &&
        (in_context & IC_MESSAGE) == 0 ) )
    {
        ECHO;
    }

    for( t = &yytext[0] ; (ch=(unsigned char)*t) != '\0'; ++t )
    {
        if (ch == '\n' || ch == '\f')
        {
            column = 0;
            ++lineat;
        } else if (ch == '\t')
            column += 8 - (column % 8);
        else
            column++;
    }

    if( save_text )
    {
            ch = (unsigned char) yytext[0];
            if( echoFlag && ch > ' ' && isascii(ch) )
                	texts = newstrcat( texts, yytext );
#if SW_WATCH
            if( !echoFlag && ch > ' ' && isascii(ch) )
                	printf( "-- symbol save prevented <%s> --\n", yytext );
#endif
    }

}   /* all_count */



void count()
{
    all_count( 1 );
}


/*  ne_count  --  Don't echo this symbol!
*/
void ne_count()
{
    all_count( 0 );
}


int check_type()
{
    extern int   lu_type PARMS((  CONST char * ));
/*
* pseudo code --- this is what it should check
*
*       if (yytext == type_name)
*               return(TYPE_NAME);
*
*       return(IDENTIFIER);
*/

    /*  If it's a known typedef type, say OK */
    if( lu_type(yytext) )
        return( TYPE_NAME );

    return(IDENTIFIER);
}   /* check_type */


    void
inc_td_cnt( )
{
    ++td_nest;
}


    void
dec_td_cnt( )
{
    if( td_nest > 0 )
    {
        --td_nest;
        if( trip_hline < 0 && yytext[0] == CH_RCURLY )
            trip_hline = 1;
    }
}   /* dec_td_cnt */



/*	    See if correct context to have message parameter.  Eg "a=b?c:d"
//      is bad.  A "PARM_LABEL" states the identifier just spotted is
//      actually part of the method selector label.   The context to
//      catch this is inside a message.  We try to separate this from
//      the "?:" operator.
*/
    int
msg_parm()
{

    if( in_context & IC_MESSAGE )
    {
        ne_count();                        /* Text picked up by grammar */
        return( PARM_LABEL );            /* Good context */
    }

    unput_last();              /* Give back the colon */
    count();
    return( IDENTIFIER );
}   /* msg_parm */



/* ------------------  OCT Preprocess Helpers  ------------------------ */

/*   take_parm  --  Gobble text up until closing paren.  Used by OCT
//                  preprocessor functions.  Returns text pointer, or
//                  NULL if something wrong, like EOF...  Front-end to
//          scan_next_word() to ensure parameter is inside of parens.
*/
    char *
take_parm()
{
    int 	c;

    if( (c=scan_next_word()) == 0 || c != CH_CLOSE_PAREN )
        return NULL;

#if SW_WATCH
    printf( "(oct_preproc) <%s>", yytext );
#endif

    return( & scan_keep[0] );
}   /* take_parm */


/*   open_method  --  When an open method symbol is detect, it is only
//                	  relative outside any {} nesting.  If we're are
//                	  nested, then simply return the symbol.
*/
    int
open_method()
{
    int 	rc ;

    if( td_nest > 0 )
    {
        count();
        rc = yytext[0];        /* Return first char of line */
    } else
    {
        ne_count();
        if( yytext[0] == '+' )
        {
            m_order = 'F' ;
            rc = OPEN_FACTORY_METHOD;
        } else
        {
            m_order = 'I' ;
            rc = OPEN_INSTANCE_METHOD; 
        }
        in_state |= IS_METHOD_DEF;
    }   /* else if not nested.. */

    return( rc );
}   /* open_method */


/* -----------------------  Translator Directives  ---------------------- */


/*   ooc_public  --  Note that we saw public directive.  Call back to
 *                   grammar to change any state info.
 */
    void
ooc_public( )
{
    extern void 	see_public();

    see_public();
    ne_count();

}	/* ooc_public */


/*   ooc_selector  --  Handle "@selector( .. )".  Converts the following
//                	   text into an internal selector code.  The text
//                	   inside parens is converted and setup as the next
//                	   token to be read.  The "@selector(..)" text is
//            ignored by not returning (in scanner definitions area above).
*/
    void
ooc_selector( )
{
    register char	*p;

    if( take_parm() == NULL )
        return ;


    /*  Pack selector, convert to internal name, then `unput' it into
    //	lex's input buffer (treated as a stack).
    */
    strremove( scan_keep, ' ' );
    asCRef_selector( scan_keep );            /* Selector stored in 'buff' */


    /*	The preproc operation has been eaten up by us.  Now stuff the
    //	selector internal code the asCRef_selector() has stored in 'buff'
    //	for us.  By unput()'ing, this token will be read next time thru
    //	the loop of yylex().  This means the text will be examined by
    //	the scanner, and the array reference will appear as another
    //	sub-expression.  Can be used inside of msg exprs!
    */
    for( p=buff+strlen(buff) ; --p >= buff ; )
    {
        unput( *p );
        --column;
    }

#if SW_WATCH
    printf( " @sel(%s) --> {%s}\n", scan_keep, buff );
#endif

}   /* ooc_selector */


/*   ooc_defs  --  Handle the @defs() directive.  Search known classes
//                   for the instance variables is has.  The string is
//                   deposited directly into the output stream.
*/
    void
ooc_defs( )
{
    extern void 	do_td_def PARMS(( char *classname ));

    if( take_parm() != NULL )
    {
        /*  The class name is now in scan_keep[].  Inspect dataset for
        //	all instance variables.  Text is sent to 'yyout'.
        */
        strremove( scan_keep, ' ' );
        do_td_defs( scan_keep );
    }

    trip_hline = -1;	/* we'll need a resynch after closing brace */

}   /* ooc_defs */



    void
ooc_includes( )
{
    extern void   out_includes PARMS(( void ));
    extern void   out_externs PARMS(( int end_flag ));

    take_parm();
    out_includes();
    out_externs( 0 );
    hash_line( 0 );               /* Resynch */
}   /* ooc_includes */



    void
ooc_encode( )
{

    take_parm();
    fputs( "sorry, @encode() not implemented\n", stdout );
    ++cnt_warnings;
}   /* ooc_encode */



/* -----------------------  The Public Part  -------------------------- */


static char    set_unget_token = FALSE;   /* TRUE returns last token again */
static int     this_tok;                  /* Save just in case */


/*   get_tok  --  The main translator calls here to read another token.
//                As 'yytext' can be defined as an array or ptr, we point
//                to it using our own string ptr.  Maintains current
//                and previous token values.
*/
    int
get_tok()
{
    extern char    *curr_name;     /* String ptr to token */
    extern int     curr_tok;       /* Token read by last function */
    extern int     prev_tok;       /* Looking Back.. */
    extern int     pp_tok;         /* Previous previous token */

    if( curr_tok != DONE && !set_unget_token )
    {
        pp_tok   = prev_tok;
        prev_tok = curr_tok;
        this_tok = yylex();
    }
    curr_tok = this_tok;
    set_unget_token = FALSE;
    curr_name = & yytext[0];        /* Access in type-independent manner */

    return( curr_tok );
}   /* get_tok */


    void
unget_tok()
{
    set_unget_token = TRUE;    	/* Return current token once more */
}


/*   peek_tok  --  Non-destructive read of next token.  Never returns
 *                 curr_name; doesn't change curr_tok.
 */
    int
peek_tok()
{

    if( !set_unget_token )
    {
        set_unget_token = TRUE;
        this_tok = yylex();
    }
	return( this_tok );
}   /* peek_tok */


